name: kcm-frontend-tests

services:

  frontend:
    image: kcm-fe-test
    build:
      context: .
      target: base
    command: "pnpm run test"
    networks:
      - internal
    environment:
      - NODE_ENV=test
      - CI=true

networks:
  internal:
