// flow-typed signature: 0bca9d6326776725f3b15dedad11b633
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30000652/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
